#!/usr/bin/env python

import argparse
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser(description='Plot conservation of a protein.')
    parser.add_argument('--input', required=True, type=str,
                        help='Input file in .agr format')
    parser.add_argument('--N', required=True, type=int,
                        help='Plot every Nth point')
    parser.add_argument('--ylim', required=True, type=float,
                        help='ylim of plot')
    parser.add_argument('--title', required=True, type=str,
                        help='Title of plot')
    args = parser.parse_args()

    input_file = args.input
    nth = args.N
    ylim = args.ylim
    title = args.title

    data = import_data(input_file)
    trimmed_data = trim_data(data, nth)
    plot_data(trimmed_data, ylim, title)

def import_data(input_file):
    with open(input_file, 'r') as file:
        frames = []
        rmsds = []
        for line in file:
            if '#' not in line:
                pair = line.split()
                frames.append(float(pair[0]))
                rmsds.append(float(pair[1]))
        data = [frames, rmsds]
    return data

def trim_data(data, nth):
    trimmed_frames = []
    trimmed_rmsds = []
    for frame, rmsd in zip(data[0], data[1]):
        if frame % nth == 0:
            trimmed_frames.append(frame)
            trimmed_rmsds.append(rmsd)
    trimmed_data = [trimmed_frames, trimmed_rmsds]
    return(trimmed_data) 

def plot_data(data, ylim, title):
    fig, ax = plt.subplots()
    plt.plot(data[0],data[1])
    plt.title(title)
    plt.xlabel('Frame')
    plt.ylabel('RMSD')
    plt.ylim(0, ylim)
    plt.margins(0)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    plt.show()
    return True

if __name__ == '__main__':
     main()
