#!/usr/bin/env python

import argparse
import matplotlib.pyplot as plt


def main():
    parser = argparse.ArgumentParser(description='Plot rmsds of multiple md sims.')
    parser.add_argument('-i', '--input', required=True, nargs='+', type=str,
                        help='Input file in .dat format')
    parser.add_argument('-l', '--labels', required=True, nargs='+', type=str,
                        help='Labels for data, in order ')
    parser.add_argument('-c', '--colors', required=False, nargs='+', type=str,
                        help='Colors for data, in order ', default=['#AEC7E8', '#98DF8A', '#FF9896', '#FFB347', '#C5B0D5'])
    parser.add_argument('-N', required=True, type=int,
                        help='Plot every Nth point')
    parser.add_argument('-y', '--ylim', required=True, type=float,
                        help='ylim of plot')
    parser.add_argument('-t', '--title', required=True, type=str,
                        help='Title of plot')
    args = parser.parse_args()

    input_files = args.input
    labels = args.labels
    colors = args.colors
    nth = args.N
    ylim = args.ylim
    title = args.title

    all_data = []
    for file in input_files:
        data = import_data(file)
        trimmed_data = trim_data(data, nth)
        all_data.append(trimmed_data)
    plot_data(all_data, ylim, title, labels, colors)

def import_data(input_file):
    with open(input_file, 'r') as file:
        frames = []
        rmsds = []
        for line in file:
            if '#' not in line:
                pair = line.split()
                frames.append(float(pair[0]))
                rmsds.append(float(pair[1]))
        data = [frames, rmsds]
    return data

def trim_data(data, nth):
    trimmed_frames = []
    trimmed_rmsds = []
    for frame, rmsd in zip(data[0], data[1]):
        if frame % nth == 0:
            trimmed_frames.append(frame)
            trimmed_rmsds.append(rmsd)
    trimmed_data = [trimmed_frames, trimmed_rmsds]
    return(trimmed_data) 

def plot_data(all_data, ylim, title, labels, colors):
    fig, ax = plt.subplots()
    for data, label, color in zip(all_data, labels, colors):
        plt.plot(data[0],data[1], label=label, color=color)
    plt.title(title)
    plt.legend(loc=1)
    plt.xlabel('Frame')
    plt.ylabel('RMSD')
    plt.ylim(0, ylim)
    plt.margins(0)
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    plt.show()
    return True

if __name__ == '__main__':
     main()
